version: "3.8"
services:
  nginx:
    restart: always
    image: nginx:latest
    networks:
      - net_app1
      - net_app2
    ports:
      - 443:443
      - 80:80
      - 8181:8181
    volumes:
      - ${NGINX_CONF_DIR}:/etc/nginx/conf.d/:ro
      - ${NGINX_CERTBOT_DIR}:/var/www/certbot/:ro
      - ${NGINX_LETSENCR_DIR}:/etc/letsencrypt/:ro
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ${NGINX_CERTBOT_DIR}:/var/www/certbot/
      - ${NGINX_LETSENCR_DIR}:/etc/letsencrypt/
networks:
  net_app1:
  net_app2:
