version: "0.1"
services:
  nginx:
    restart: always
    image: nginx:latest
    networks:
      - net_nginx
    ports:
      - 443:443
      - 80:80
      - 8181:8181
    volumes:
      - ${NGINX_CONF_DIR}:/etc/nginx/conf.d/:ro
      - ${NGINX_LETSENCR_DIR}:/var/www/certbot/:ro
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ${NGINX_LETSENCR_DIR}:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
